name: Develop Pull Request (CI)

on:
  pull_request:
    branches: [develop]

jobs:
  deploy:
    name: 🚧 Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: cd factory/simulators && npm install

      - name: 🕵️‍♂️  Lint
        run: cd factory/simulators && npm run-script lint --if-present

      - name: 🧪  Test
        run: cd factory/simulators && npm run test --if-present

      - name: 🚧  Build App
        run: cd factory/simulators && npm run build

      # TODO change name and key, set version & deploy
