name: Develop Deploy After Merge (CD)

on:
  pull_request:
    branches: [develop]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: |
          cd factory/simulators
          npm install

      - name: 🚧  Build App
        run: |
          cd factory/simulators
          npm run-script c8ycli build

      - name: 🚀 Deploy
        run: |
          cd factory/simulators
          npm run-script c8ycli 'deploy -u https://psfactory.eu-latest.cumulocity.com -T ${{ secrets.DEV_DEPLOY_TENANT }} -U "${{ secrets.DEV_DEPLOY_USER }}" -P "${{ secrets.DEV_DEPLOY_PASS }}" ./dist/apps/simulators'
