name: Develop Deploy After Merge (CD)

on:
  pull_request:
    branches: [develop]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env:
          DEV_DEPLOY_USER: ${{ secrets.DEV_DEPLOY_USER }}
          DEV_DEPLOY_TENANT: ${{ secrets.DEV_DEPLOY_TENANT }}
          DEV_DEPLOY_PASS: ${{ secrets.DEV_DEPLOY_PASS }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: |
          cd factory/simulators
          npm install

      - name: 🚧  Build App
        run: |
          cd factory/simulators
          npm run-script c8ycli build --app.key="advanced-simulator-dev" --app.name="Advanced Simulators DEV" --app.contextPath="advanced-simulators-dev"

      - name: 🚀 Deploy
        run: |
          cd factory/simulators
          npm run-script c8ycli deploy -u https://psfactory.eu-latest.cumulocity.com -T $DEV_DEPLOY_TENANT -U "$DEV_DEPLOY_USER" -P "$DEV_DEPLOY_PASS" ./dist/apps/simulators
