name: Version Tag

on:
  push:
    branches: [main]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  NODE_VERSION: '12'

jobs:
  build:
    name: 🚧 Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Node.js dependencies
        run: npm install

      - name: 🕵️‍♂️  Lint
        run: npm run-script lint --if-present

      - name: 🧪  Test
        run: npm test --if-present

      - name: Cache dist folder
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/cache@v2
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}

      - name: 🚧  Build
        run: npm run build --if-present

  package:
    name: 🎁 Package Release Asset
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Set RELEASE_VERSION env variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Cache dist folder
        uses: actions/cache@v2
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}

      - name: 🎁  Zip Application
        run: |
          cd dist/apps/simulators
          zip -r -q ../../../advanced-simulator-${{ env.RELEASE_VERSION }}.zip *
          cd ../../..

      - name: 🔨  Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: ✈  Upload Release Asset Administration
        id: upload-release-asset-admin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./advanced-simulator-${{ env.RELEASE_VERSION }}.zip
          asset_name: advanced-simulator-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
